# Generated by Django 4.1.3 on 2022-11-15 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=12)),
                ('dataNascimento', models.DateField()),
            ],
        ),
    ]
